### ISSUE TITLE
[Enhancement] Execute commands in a new thread

### ISSUE THREAD

**Issue by pindab0ter** [jagrosh/JDA-Utilities#101]
[download]: https://bintray.com/jagrosh/maven/JDA-Utilities/_latestVersion
[guild]: https://discord.gg/0hMr4ce0tIk3pSjp
[stack overflow]: https://stackoverflow.com/questions/tagged/java
[issues]: https://github.com/JDA-Applications/JDA-Utilities/issues
[jda-issues]: https://github.com/DV8FromTheWorld/JDA/issues
[examples-module]: https://github.com/JDA-Applications/JDA-Utilities/tree/master/examples
[jda-u-projects]: https://github.com/JDA-Applications/JDA-Utilities#projects

#### Issue Checklist
Please follow the following steps before opening this issue.<br>
Issues that do not complete the checklist may be closed without any help.

- [x] I have checked for similar issues on the [issue tracker][issues].
- [x] I have updated to the [latest version][download] of JDA-Utilities.
- [x] I have checked the branches or the maintainers' PRs for upcoming features/bug fixes.

> The issue tracker is reserved for issues, errors, and feature requests related 
> to JDA-Utilities, and not questions and other requests for help.
>
> - For examples, check out the [examples module][examples-module] or the list 
>   of [JDA-Utilities projects][jda-u-projects].
> - For questions join the [official JDA discord server][guild] and ask them 
>   in our `#jda-utilities` channel.
> - For general programming questions, visit [StackOverflow][stack overflow].

#### Issue Information
Check all that apply:

- [x] This is a bug report about an error, issue, or bug in JDA-Utilities.
- [ ] I have been able to consistently reproduce this bug.
- [x] This is a feature request for the JDA-Utilities library.

> This issue tracker **does not** assist or handle issues with the JDA library.<br>
> For JDA related issues, visit the [JDA issue tracker][jda-issues]
> and open an issue there.

#### Description

Currently every command is executed sequentially. In practice this means that sometimes a user will have to wait for a command to finish running which isn't clear to that user. While running heavy code asynchronously within the `execute` function is a solution for this, a much better solution would be to simply run every command asynchronously.

**Comment by jagrosh** [comment]
There's a few reasons why this shouldn't be changed:
- For most commands, you _don't_ want to run them asynchronously. Generally you should only run commands async if they do processing that takes a long time or are making external calls; doing everything async can lead to race conditions, and can also have worse performance.
- You can already do this; we provide `CommandEvent#async(Runnable)` so that you can run the contents of a specific command asynchronously
- If you want to do everything async, you should just write a custom event manager, as JDA-Utils' command client is just an event listener, not an event manager. We shouldn't have the internals of this event listener deviate from the developer's intended event manager system.
