### ISSUE TITLE
[Suggestion] ownerCommand

### ISSUE THREAD

**Issue by Artuto** [jagrosh/JDA-Utilities#15]
When setting on a command ```this.ownerCommand = true``` send an error message if a non-owner user tries to execute the command.

**Comment by Shengaero** [comment]
This is intentional.
From a developer standpoint, it wouldn't be accessible at all, so the way we see it is that it should only exist for the developer.
If you personally wanted to have it respond you would simply need to set the following as the command's category:
```java
this.category = new Category("Owner Command", event -> {
    if(!event.isOwner() && !event.isCoOwner())
    {
        event.replyError("You don't have access!");
        return false;
    }
    return true;
});
```
or alternatively
```java
this.category = new Category("Owner Command", "You don't have access!", event -> event.isOwner() || event.isCoOwner()));
```
which should provide the same idea or effect, although the prefixed error emoji may be missing.
