### ISSUE TITLE
[Suggestion] Could benefit from a tutorial on how to use the CommandClient and everything else

### ISSUE THREAD

**Issue by lyssieth** [jagrosh/JDA-Utilities#8]
'cause right now, I'm confused.

**Comment by Shengaero** [comment]
If you took a look at the README.md, you'd probably have noticed the link to the example bot: https://github.com/jagrosh/ExampleBot

**Comment by Shengaero** [comment]
There are also two other example bots at the bottom of the read me if you want more examples.

**Comment by lyssieth** [comment]
The main example bot wasn't too useful, especially for making your own
commands.

Will take a look at the other two.

**Comment by Shengaero** [comment]
Well if you're looking for example commands there is also four examples here: https://github.com/jagrosh/JDA-Utilities/tree/master/src/main/java/me/jagrosh/jdautilities/commandclient/examples 
And again, you can always check the examples jagrosh has made at the bottom of the README.md for more examples of commands.

**Comment by lyssieth** [comment]
I'll play around a bit, maybe (extremely maybe) even write my own guide for making your own commands and such. Mostly for self-refrence, but for others as well.

I found this project today while searching for JDA pagination stuff, so I haven't had much time to use it due to school and other similar reasons, including but not limited to friends, food and Windows Update.

**Comment by Shengaero** [comment]
I think it wouldn't hurt to create a more in depth guide on creating specifically commands, I would also second that idea, but it will have to wait until v1.0

**Comment by lyssieth** [comment]
Well, I'll be watching, and learning.

**Comment by Shengaero** [comment]
I am currently writing the wiki for JDA-Utilities, and I figure there will be more than enough guides + usage documentation after it's completely done.

This issue has been open since March, it's now September and I believe it's come time to close.

If you have any more questions regarding JDA-Utilities, the [wiki](https://github.com/JDA-Applications/JDA-Utilities/wiki/) and documentation work will more than likely be able to provide you with an answer.
